/**
 * 
 * @author Axel, Jonne
 *
 */
public enum Jatsiyhdistelma {
	YKKOSET, KAKKOSET, KOLMOSET, NELOSET, VIITOSET, KUUTOSET, PARI, KAKSI_PARIA, KOLME_SAMAA, NELJA_SAMAA, PIKKUSUORA, ISOSUORA, TAYSKASI, SATTUMA, YATZY

}
